### ISSUE TITLE
Unable to Start Bot

### ISSUE THREAD

**Issue by zluckytraveler** [EthanC/Perplex#12]
Bot will not start and do not know how to fix it.

Terminal Output Error
```
Lucky@Luckys-Mac Perplex % python3 perplex.py
Traceback (most recent call last):
  File "/Applications/Apps/Programs/Perplex/perplex.py", line 9, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

config.json
```"logging": {
        "severity": "INFO"
    },
    "plex": {
        "username": "(REDACTED)",
        "password": "(REDACTED)",
        "twoFactor": false,
        "servers": ["Plex 'N Chill"],
        "users": ["Zak"]
    },
    "tmdb": {
        "enable": true,
        "apiKey": "(redacted)"
    },
    "discord": {
        "appId": (REDACTED),
        "minimal": false
    }
}```

**Comment by EthanC** [comment]
You haven't installed the required dependencies, see the [README](https://github.com/EthanC/Perplex#readme).

**Comment by zluckytraveler** [comment]
@EthanC The dependancies have already been installed, I thoroughly read the readme document, as you can see all requirements have been met.

```
Lucky@Luckys-Mac Perplex % pip3 install pyproject.toml
Requirement already satisfied: pyproject.toml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.0.10)
Requirement already satisfied: setuptools>=42 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyproject.toml) (58.1.0)
Requirement already satisfied: toml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyproject.toml) (0.10.2)
Requirement already satisfied: wheel in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyproject.toml) (0.37.1)
Requirement already satisfied: jsonschema in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyproject.toml) (4.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema->pyproject.toml) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema->pyproject.toml) (21.4.0)

Lucky@Luckys-Mac Perplex % python3 perplex.py
Traceback (most recent call last):
  File "/Applications/Apps/Programs/Perplex/perplex.py", line 9, in <module>
    import httpx
ModuleNotFoundError: No module named httpx
```

**Comment by EthanC** [comment]
You've installed a literal package called [`pyproject.toml`](https://pypi.org/project/pyproject-toml/), not the packages listed in Perplex's [`pyproject.toml`](https://github.com/EthanC/Perplex/blob/main/pyproject.toml).

**Comment by zluckytraveler** [comment]
@EthanC then how do I install the file? I’ve never installed a .toml file before, and couldn’t find any instruction on how to install that file in your README.
